// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;


import frc.robot.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.PneumaticsModuleType;
import edu.wpi.first.wpilibj.Solenoid;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class Pneumatics extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
public static final int SOLENOID_1_PORT = 0;
public static final int DRIVE_LEFT_PORT = 0;
public static final int DRIVE_RIGHT_PORT = 1;
public static final double DRIVE_SPEED = 0.5;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
private Compressor compressor;
private Solenoid solenoid1;
private Solenoid solenoid2;
private Solenoid solenoid3;
private Solenoid solenoid4;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    /**
    *
    */
    public Pneumatics() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
compressor = new Compressor(0, PneumaticsModuleType.REVPH);
 addChild("Compressor",compressor);
 

solenoid1 = new Solenoid(0, PneumaticsModuleType.REVPH, 0);
 addChild("Solenoid 1", solenoid1);
 

solenoid2 = new Solenoid(0, PneumaticsModuleType.REVPH, 1);
 addChild("Solenoid 2", solenoid2);
 

solenoid3 = new Solenoid(0, PneumaticsModuleType.REVPH, 2);
 addChild("Solenoid 3", solenoid3);
 

solenoid4 = new Solenoid(0, PneumaticsModuleType.REVPH, 3);
 addChild("Solenoid 4", solenoid4);
 


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run

    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

